name: Build Solana Program

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Docker
      run: |
        # Use a development-focused Docker image
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          rust:1.90.0-slim \
          bash -c "
            apt-get update && apt-get install -y curl wget build-essential pkg-config libssl-dev
            sh -c \"\$(curl -sSfL https://release.solana.com/v1.18.4/install)\"
            export PATH=\"/root/.local/share/solana/install/active_release/bin:\$PATH\"
            cargo install --git https://github.com/solana-labs/solana.git solana-cargo-build-sbf --locked
            cargo install --git https://github.com/solana-labs/solana.git solana-cargo-test-sbf --locked
            cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
            avm install 0.31.1
            avm use 0.31.1
            cd spin_wheel && anchor build
          "
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: solana-program
        path: spin_wheel/target/deploy/*.so
        retention-days: 30
