name: Build Solana Program

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Docker
      run: |
        # Use a development-focused Docker image
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          ghcr.io/coral-xyz/anchor:0.31.1 \
          bash -c "
            cd spin_wheel && anchor build
          "
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: solana-program
        path: spin_wheel/target/deploy/*.so
        retention-days: 30
